version: "3.3"

services:
  localstack:
    image: localstack/localstack:latest
    networks:
      - localstack-net
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=dynamodb,s3,sqs,kinesis,lambda
      - EDGE_BIND_HOST=0.0.0.0
      - LAMBDA_REMOTE_DOCKER=0
      - DEFAULT_REGION=eu-west-3
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
     
networks:
  localstack-net:
    external: false
    driver: bridge